### ISSUE TITLE
can I change sandbox directory?

### ISSUE THREAD

**Issue by tico88612** [silverneko/miku#4]
My system is debian 8.
When I submission. it said "Cannot write /sys/fs/cgroup/memory/box-10/tasks : No such file or directory"
because have some permission problem.
where can I change sandbox directory?
 thanks

**Comment by silverneko** [comment]
`/sys/fs/cgroup/memory/box-10/tasks` 並不是 sandbox directory，而是 cgroup 設定資源管理的 api，我建議你檢查看看你的系統有沒有安裝並且啟用 cgroup，或是 hack 這個 [檔案](https://github.com/silverneko/miku/blob/master/isolate/isolate.c)，或是從 [上游](https://github.com/cms-dev/isolate) 抓新版的 sandbox。

**Comment by tico88612** [comment]
一定要啟用cgroup嗎？
我有試過hack檔案，可是記憶體超出限制，系統不會有所反應（EX. int s[100000000000]）這早就MLE了
我抓新版似乎有問題

**Comment by silverneko** [comment]
因為這個 sandbox 是使用 cgroup 實作資源管理的，所以一定要啟用 cgroup 沒錯，除非改用別的 sandbox 或是改用別種資源管理方法。
至於沒有觸發記憶體限制的問題，可以給出完整的 case 嗎？不然從你提供的資訊來看，僅僅是寫 `int s[100000000000]` 的確有可能不會觸發 MLE，因為 linux 的記憶體配置是 "on-demand" 的，系統只會限制你 "實際用到的" 記憶體數量而不是你 "宣稱用到的" 記憶體數量，所以如果你配置了一塊超大的記憶體但是卻只用到其中的一小部分，那麼就有可能不會觸發記憶體限制。這個部分可以看看 linux 實作 virtual memory / resident memory 的方法。

**Comment by tico88612** [comment]
I didn't open cgroup memory.
Because Debian default setting is no open memory.
In my old judge-[HustOJ](https://github.com/svn2github/hustoj/blob/master/wiki/ojback.wiki) 
```
#include<stdio.h>
int main()
{
int aa[10000000000];
for(int i=0;i<10000;i++)
 aa[i]=i;
printf("Hello World");
return 0;
}
```
It said Runtime Error(Segmentation fault). But TIOJ sandbox said AC.
Maybe sandbox was something different.
Thank to your patient, my problem is solved.

**Comment by silverneko** [comment]
<s> 我想這可能是因為 HustOJ 使用的 setrlimit() 限制的是 virtual memory space size，而 isolate 使用的 cgroup 限制的是 resident memory size，所以這個例子你用到的 virtual memory 有 10000000000 這麼多但是 resident memory 只有用到 10000，因此 HustOJ 應該是偵測到 violate 了 VM or stack limit 而 cgroup 不會回報 segfault。 </s> This is wrong, ignore it.
我剛剛看了一下我使用 sandbox 的方法，發現我也是用 setrlimit() 限制的（抱歉因為這是滿久以前寫的程式，所以沒有記得很清楚當時的細節），所以照理講 HustOJ 跟 TIOJ 的結果應該要一樣的，否則這不合理，可能的解釋有可能是 HustOJ 有限制 stack size 而 tioj 沒有限制，或者也有可能是編譯器把 for loop & 大陣列優化掉了。你在測試的時候應該沒有用 -O2 吧？

我剛剛回去看了一下 isolate 的用法，可以提供你幾個解決方法：
1. 按照 [這裡](https://github.com/cms-dev/isolate/blob/master/isolate.1.txt#L245) 的方法設定你系統的 cgroup。
2. 把 [這個檔案](https://github.com/silverneko/miku/blob/master/src/sandbox.cpp#L15) 的 line 15 44 55 改掉試試看，我想起來其實 isolate 預設也是用 setrlimit() 限制記憶體的，之所以當初會使用 cgroup 是因為想要在 judge 上支援 multithread / multiprocess 程式（不過後來也沒有產生這個需求）。

**Comment by tico88612** [comment]
解決方法應該是分開的，一個是直接用cgroup，一個是關閉isolate cgroup。

1. 因為有點看不懂，網路上cgroup的中文介紹也有點看不懂，決定用2.

2. 改掉是指把line 15 44 55 做註解嗎？ 因為我試過了，還是會把上面的程式碼打AC

**Comment by silverneko** [comment]
沒錯兩個方法是分開的，是二選一。我這邊提供的只是讓 isolate 可以不需要 cgroup 執行的方法；關於那段程式碼會回報 AC or MLE 的問題我只有之前的那些猜測而已，因為我自己測試/使用的結果沒有問題。
